---
Name: foxystripe-reviews
---
ProductPage:
  extensions:
    - HasReviews
ProductPage_Controller:
  extensions:
    - HasReviews_Controller
SiteConfig:
  extensions:
    - ReviewSiteConfigExtension